# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cm/codes/c++/glpai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cm/codes/c++/glpai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cm/codes/c++/glpai/CMakeFiles /home/cm/codes/c++/glpai//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cm/codes/c++/glpai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pai

# Build rule for target.
pai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pai
.PHONY : pai

# fast build rule for target.
pai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/build
.PHONY : pai/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/main.cpp.s
.PHONY : main.cpp.s

tools/Camera.o: tools/Camera.cpp.o
.PHONY : tools/Camera.o

# target to build an object file
tools/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Camera.cpp.o
.PHONY : tools/Camera.cpp.o

tools/Camera.i: tools/Camera.cpp.i
.PHONY : tools/Camera.i

# target to preprocess a source file
tools/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Camera.cpp.i
.PHONY : tools/Camera.cpp.i

tools/Camera.s: tools/Camera.cpp.s
.PHONY : tools/Camera.s

# target to generate assembly for a file
tools/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Camera.cpp.s
.PHONY : tools/Camera.cpp.s

tools/CubeMap.o: tools/CubeMap.cpp.o
.PHONY : tools/CubeMap.o

# target to build an object file
tools/CubeMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/CubeMap.cpp.o
.PHONY : tools/CubeMap.cpp.o

tools/CubeMap.i: tools/CubeMap.cpp.i
.PHONY : tools/CubeMap.i

# target to preprocess a source file
tools/CubeMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/CubeMap.cpp.i
.PHONY : tools/CubeMap.cpp.i

tools/CubeMap.s: tools/CubeMap.cpp.s
.PHONY : tools/CubeMap.s

# target to generate assembly for a file
tools/CubeMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/CubeMap.cpp.s
.PHONY : tools/CubeMap.cpp.s

tools/GameObject.o: tools/GameObject.cpp.o
.PHONY : tools/GameObject.o

# target to build an object file
tools/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/GameObject.cpp.o
.PHONY : tools/GameObject.cpp.o

tools/GameObject.i: tools/GameObject.cpp.i
.PHONY : tools/GameObject.i

# target to preprocess a source file
tools/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/GameObject.cpp.i
.PHONY : tools/GameObject.cpp.i

tools/GameObject.s: tools/GameObject.cpp.s
.PHONY : tools/GameObject.s

# target to generate assembly for a file
tools/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/GameObject.cpp.s
.PHONY : tools/GameObject.cpp.s

tools/Light.o: tools/Light.cpp.o
.PHONY : tools/Light.o

# target to build an object file
tools/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Light.cpp.o
.PHONY : tools/Light.cpp.o

tools/Light.i: tools/Light.cpp.i
.PHONY : tools/Light.i

# target to preprocess a source file
tools/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Light.cpp.i
.PHONY : tools/Light.cpp.i

tools/Light.s: tools/Light.cpp.s
.PHONY : tools/Light.s

# target to generate assembly for a file
tools/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Light.cpp.s
.PHONY : tools/Light.cpp.s

tools/Program.o: tools/Program.cpp.o
.PHONY : tools/Program.o

# target to build an object file
tools/Program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Program.cpp.o
.PHONY : tools/Program.cpp.o

tools/Program.i: tools/Program.cpp.i
.PHONY : tools/Program.i

# target to preprocess a source file
tools/Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Program.cpp.i
.PHONY : tools/Program.cpp.i

tools/Program.s: tools/Program.cpp.s
.PHONY : tools/Program.s

# target to generate assembly for a file
tools/Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Program.cpp.s
.PHONY : tools/Program.cpp.s

tools/SceneManager.o: tools/SceneManager.cpp.o
.PHONY : tools/SceneManager.o

# target to build an object file
tools/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SceneManager.cpp.o
.PHONY : tools/SceneManager.cpp.o

tools/SceneManager.i: tools/SceneManager.cpp.i
.PHONY : tools/SceneManager.i

# target to preprocess a source file
tools/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SceneManager.cpp.i
.PHONY : tools/SceneManager.cpp.i

tools/SceneManager.s: tools/SceneManager.cpp.s
.PHONY : tools/SceneManager.s

# target to generate assembly for a file
tools/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SceneManager.cpp.s
.PHONY : tools/SceneManager.cpp.s

tools/Shader.o: tools/Shader.cpp.o
.PHONY : tools/Shader.o

# target to build an object file
tools/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Shader.cpp.o
.PHONY : tools/Shader.cpp.o

tools/Shader.i: tools/Shader.cpp.i
.PHONY : tools/Shader.i

# target to preprocess a source file
tools/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Shader.cpp.i
.PHONY : tools/Shader.cpp.i

tools/Shader.s: tools/Shader.cpp.s
.PHONY : tools/Shader.s

# target to generate assembly for a file
tools/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Shader.cpp.s
.PHONY : tools/Shader.cpp.s

tools/SkyBox.o: tools/SkyBox.cpp.o
.PHONY : tools/SkyBox.o

# target to build an object file
tools/SkyBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SkyBox.cpp.o
.PHONY : tools/SkyBox.cpp.o

tools/SkyBox.i: tools/SkyBox.cpp.i
.PHONY : tools/SkyBox.i

# target to preprocess a source file
tools/SkyBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SkyBox.cpp.i
.PHONY : tools/SkyBox.cpp.i

tools/SkyBox.s: tools/SkyBox.cpp.s
.PHONY : tools/SkyBox.s

# target to generate assembly for a file
tools/SkyBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/SkyBox.cpp.s
.PHONY : tools/SkyBox.cpp.s

tools/Texture.o: tools/Texture.cpp.o
.PHONY : tools/Texture.o

# target to build an object file
tools/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Texture.cpp.o
.PHONY : tools/Texture.cpp.o

tools/Texture.i: tools/Texture.cpp.i
.PHONY : tools/Texture.i

# target to preprocess a source file
tools/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Texture.cpp.i
.PHONY : tools/Texture.cpp.i

tools/Texture.s: tools/Texture.cpp.s
.PHONY : tools/Texture.s

# target to generate assembly for a file
tools/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Texture.cpp.s
.PHONY : tools/Texture.cpp.s

tools/Transform.o: tools/Transform.cpp.o
.PHONY : tools/Transform.o

# target to build an object file
tools/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Transform.cpp.o
.PHONY : tools/Transform.cpp.o

tools/Transform.i: tools/Transform.cpp.i
.PHONY : tools/Transform.i

# target to preprocess a source file
tools/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Transform.cpp.i
.PHONY : tools/Transform.cpp.i

tools/Transform.s: tools/Transform.cpp.s
.PHONY : tools/Transform.s

# target to generate assembly for a file
tools/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Transform.cpp.s
.PHONY : tools/Transform.cpp.s

tools/U0.o: tools/U0.cpp.o
.PHONY : tools/U0.o

# target to build an object file
tools/U0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/U0.cpp.o
.PHONY : tools/U0.cpp.o

tools/U0.i: tools/U0.cpp.i
.PHONY : tools/U0.i

# target to preprocess a source file
tools/U0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/U0.cpp.i
.PHONY : tools/U0.cpp.i

tools/U0.s: tools/U0.cpp.s
.PHONY : tools/U0.s

# target to generate assembly for a file
tools/U0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/U0.cpp.s
.PHONY : tools/U0.cpp.s

tools/UI_Element.o: tools/UI_Element.cpp.o
.PHONY : tools/UI_Element.o

# target to build an object file
tools/UI_Element.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/UI_Element.cpp.o
.PHONY : tools/UI_Element.cpp.o

tools/UI_Element.i: tools/UI_Element.cpp.i
.PHONY : tools/UI_Element.i

# target to preprocess a source file
tools/UI_Element.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/UI_Element.cpp.i
.PHONY : tools/UI_Element.cpp.i

tools/UI_Element.s: tools/UI_Element.cpp.s
.PHONY : tools/UI_Element.s

# target to generate assembly for a file
tools/UI_Element.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/UI_Element.cpp.s
.PHONY : tools/UI_Element.cpp.s

tools/VertexData.o: tools/VertexData.cpp.o
.PHONY : tools/VertexData.o

# target to build an object file
tools/VertexData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/VertexData.cpp.o
.PHONY : tools/VertexData.cpp.o

tools/VertexData.i: tools/VertexData.cpp.i
.PHONY : tools/VertexData.i

# target to preprocess a source file
tools/VertexData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/VertexData.cpp.i
.PHONY : tools/VertexData.cpp.i

tools/VertexData.s: tools/VertexData.cpp.s
.PHONY : tools/VertexData.s

# target to generate assembly for a file
tools/VertexData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/VertexData.cpp.s
.PHONY : tools/VertexData.cpp.s

tools/Window.o: tools/Window.cpp.o
.PHONY : tools/Window.o

# target to build an object file
tools/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Window.cpp.o
.PHONY : tools/Window.cpp.o

tools/Window.i: tools/Window.cpp.i
.PHONY : tools/Window.i

# target to preprocess a source file
tools/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Window.cpp.i
.PHONY : tools/Window.cpp.i

tools/Window.s: tools/Window.cpp.s
.PHONY : tools/Window.s

# target to generate assembly for a file
tools/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/Window.cpp.s
.PHONY : tools/Window.cpp.s

tools/cmMath/matrix4.o: tools/cmMath/matrix4.cpp.o
.PHONY : tools/cmMath/matrix4.o

# target to build an object file
tools/cmMath/matrix4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/matrix4.cpp.o
.PHONY : tools/cmMath/matrix4.cpp.o

tools/cmMath/matrix4.i: tools/cmMath/matrix4.cpp.i
.PHONY : tools/cmMath/matrix4.i

# target to preprocess a source file
tools/cmMath/matrix4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/matrix4.cpp.i
.PHONY : tools/cmMath/matrix4.cpp.i

tools/cmMath/matrix4.s: tools/cmMath/matrix4.cpp.s
.PHONY : tools/cmMath/matrix4.s

# target to generate assembly for a file
tools/cmMath/matrix4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/matrix4.cpp.s
.PHONY : tools/cmMath/matrix4.cpp.s

tools/cmMath/vectors.o: tools/cmMath/vectors.cpp.o
.PHONY : tools/cmMath/vectors.o

# target to build an object file
tools/cmMath/vectors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/vectors.cpp.o
.PHONY : tools/cmMath/vectors.cpp.o

tools/cmMath/vectors.i: tools/cmMath/vectors.cpp.i
.PHONY : tools/cmMath/vectors.i

# target to preprocess a source file
tools/cmMath/vectors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/vectors.cpp.i
.PHONY : tools/cmMath/vectors.cpp.i

tools/cmMath/vectors.s: tools/cmMath/vectors.cpp.s
.PHONY : tools/cmMath/vectors.s

# target to generate assembly for a file
tools/cmMath/vectors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pai.dir/build.make CMakeFiles/pai.dir/tools/cmMath/vectors.cpp.s
.PHONY : tools/cmMath/vectors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pai"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tools/Camera.o"
	@echo "... tools/Camera.i"
	@echo "... tools/Camera.s"
	@echo "... tools/CubeMap.o"
	@echo "... tools/CubeMap.i"
	@echo "... tools/CubeMap.s"
	@echo "... tools/GameObject.o"
	@echo "... tools/GameObject.i"
	@echo "... tools/GameObject.s"
	@echo "... tools/Light.o"
	@echo "... tools/Light.i"
	@echo "... tools/Light.s"
	@echo "... tools/Program.o"
	@echo "... tools/Program.i"
	@echo "... tools/Program.s"
	@echo "... tools/SceneManager.o"
	@echo "... tools/SceneManager.i"
	@echo "... tools/SceneManager.s"
	@echo "... tools/Shader.o"
	@echo "... tools/Shader.i"
	@echo "... tools/Shader.s"
	@echo "... tools/SkyBox.o"
	@echo "... tools/SkyBox.i"
	@echo "... tools/SkyBox.s"
	@echo "... tools/Texture.o"
	@echo "... tools/Texture.i"
	@echo "... tools/Texture.s"
	@echo "... tools/Transform.o"
	@echo "... tools/Transform.i"
	@echo "... tools/Transform.s"
	@echo "... tools/U0.o"
	@echo "... tools/U0.i"
	@echo "... tools/U0.s"
	@echo "... tools/UI_Element.o"
	@echo "... tools/UI_Element.i"
	@echo "... tools/UI_Element.s"
	@echo "... tools/VertexData.o"
	@echo "... tools/VertexData.i"
	@echo "... tools/VertexData.s"
	@echo "... tools/Window.o"
	@echo "... tools/Window.i"
	@echo "... tools/Window.s"
	@echo "... tools/cmMath/matrix4.o"
	@echo "... tools/cmMath/matrix4.i"
	@echo "... tools/cmMath/matrix4.s"
	@echo "... tools/cmMath/vectors.o"
	@echo "... tools/cmMath/vectors.i"
	@echo "... tools/cmMath/vectors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

